name: stagelive
description: "A new Flutter project for StageLive."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- UI & Fonts ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  
  image_picker: ^1.1.2
  firebase_storage: ^11.7.2

  # --- State Management & Maps ---
  provider: ^6.1.1
  flutter_map: ^6.1.0
  flutter_polyline_points: ^3.1.0
  
  # --- Networking & Utils ---
  http: ^1.1.0
  intl: ^0.19.0
  uuid: ^4.3.3
  flutter_foreground_task: ^9.2.2

  # --- FIREBASE (Versioni stabili e compatibili) ---
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Rimosso il blocco assets vuoto o mal formattato
  # Se caricherai immagini, dovrai aggiungere:
  # assets:
  #   - assets/images/